function [opt] = chooseMask(opt, roiSource)

% this is a switch case, according to the action, we choose with ROIs to be
% used

% subjectSphere: functional spherical rois for each subject
% groupSphere: functional spherical rois for the group
% glasserMotor: based on glasser atlas
% glasserMtMst: based on glasser atlas

    switch roiSource

        case 'subjectSphere'
            radiusNb=opt.maskRadiusNb;
            opt.maskPath = fullfile(fileparts(mfilename('fullpath')), '..','..', 'outputs','derivatives' ,'bidspm-roi','subjectSphere',strcat('sub-',subID));
            opt.maskName = {strcat('sub-',num2str(subID),'_hemi-L_space-MNI_label-lhMT_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-',num2str(subID),'_hemi-R_space-MNI_label-rhMT_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-',num2str(subID),'_hemi-L_space-MNI_label-lS1_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-',num2str(subID),'_hemi-L_space-MNI_label-lPC_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-',num2str(subID),'_hemi-R_space-MNI_label-rPC_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-',num2str(subID),'_hemi-L_space-MNI_label-lMTt_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-',num2str(subID),'_hemi-R_space-MNI_label-rMTt_radiusNb-',num2str(radiusNb), '.nii'),...
                };

        case 'groupSphere'
            radiusNb=opt.maskRadiusNb;
            opt.maskPath = fullfile(fileparts(mfilename('fullpath')), '..','..','outputs','derivatives' ,'bidspm-roi','groupSphere','sub-ALL');
            opt.maskName = {strcat('sub-','ALL','_hemi-L_space-MNI_label-lhMT_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-','ALL','_hemi-R_space-MNI_label-rhMT_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-','ALL','_hemi-L_space-MNI_label-lS1_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-','ALL','_hemi-L_space-MNI_label-lPC_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-','ALL','_hemi-R_space-MNI_label-rPC_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-','ALL','_hemi-L_space-MNI_label-lMTt_radiusNb-',num2str(radiusNb), '.nii'), ...
                strcat('sub-','ALL','_hemi-R_space-MNI_label-rMTt_radiusNb-',num2str(radiusNb), '.nii'),...
                };    

        case 'glasserMotor'
            opt.maskPath = fullfile(fileparts(mfilename('fullpath')), '..','..','outputs','derivatives' ,'bidspm-glasser-roi',...
                'derivatives' ,'bidspm-roi','group');
            opt.maskName = {strcat('r','hemi-L_space-MNI_label-4','_mask','.nii'), ...
                strcat('r','hemi-R_space-MNI_label-4','_mask','.nii'), ...
                };

        case 'glasserMtMst'
            opt.maskPath = fullfile(fileparts(mfilename('fullpath')), '..','..','outputs','derivatives' ,'bidspm-glasser-roi',...
                'derivatives' ,'bidspm-roi','group');
            opt.maskName = {strcat('r','hemi-L_space-MNI_label-MT','_mask','.nii'), ...
                strcat('r','hemi-R_space-MNI_label-MT','_mask','.nii'), ...
                strcat('r','hemi-L_space-MNI_label-MST','_mask','.nii'), ...
                strcat('r','hemi-R_space-MNI_label-MST','_mask','.nii'), ...
                };       
    end
end